### ISSUE TITLE
formalize `ryder-bridge` spec

### ISSUE THREAD

**Issue by chazkiker2** [Light-Labs/ryder-bridge#11]
This is a collective effort issue. 

I would love to further clarify the `ryder-bridge` spec, including an explicit feature-set that we want to actively pursue as well as an outline for how we plan to approach each front. 

Keep in mind that the highest priorities right now are: 

- get a WebSocket API up and running
- make the RyderSerial accessible THROUGH that API
- find a way to Sign In to the Stacks Wallet Web extension by way of our WebSocket API

**Comment by friedger** [comment]
This is now (to be) implemented in https://github.com/Light-Labs/ryder-bridge-rust
