### ISSUE TITLE
Replace SocketIO with ws

### ISSUE THREAD

**Issue by MarvinJanssen** [Light-Labs/ryder-bridge#12]
I'm not a huge fan of SocketIO so I opened this self-assigned issue to track a migration to `ws`.

**Comment by dantrevino** [comment]
OT: Why dont you like socketio?  Thinking of adding it to a project ...

**Comment by MarvinJanssen** [comment]
It add a bunch of custom protocol complexity and client overhead on top. If you ever want to build a non-JS client for your SocketIO service you'll have a bad time. You'll be much better off using [ws](https://github.com/websockets/ws). It's a lot faster and you can still just send JSON strings if you insist. If the SocketIO API is what is attractive: I'm sure it can be recreated with ws with minimal effort.

**Comment by MarvinJanssen** [comment]
Take a look at draft #13.

**Comment by friedger** [comment]
We are using websockets in https://github.com/Light-Labs/ryder-bridge-rust
