### ISSUE TITLE
understand how `Stacks Wallet Web` manages Authentication & Authorization

### ISSUE THREAD

**Issue by chazkiker2** [Light-Labs/ryder-bridge#9]
We need to figure out exactly how the `stacks-wallet-web` allows people to sign in. The purpose of this is so that we can figure out what we need to do with the `ryder-bridge` in order to tie the two together.

Objectives: 
- [ ] find the exact files/components in `stacks-wallet-web` that are relevant for signing in to an account
- [ ] **bonus points** if you can propose an approach for a layer that would tie together the `ryder-bridge` and the `stacks-wallet-web`

**Comment by MarvinJanssen** [comment]
We'd want to introduce a `WalletProvider` interface in `stacks-wallet-web` with an implementation for current behaviour and one that connects to the Ryder Bridge.

**Comment by chazkiker2** [comment]
@MarvinJanssen so it seems like a lot of the "wallet" logic in `stacks-wallet-web` comes from the `@stacks/wallet-sdk`

if we're so focused on merging with Stacks at this point, I wonder to some extent if it would be appropriate to focus on merging our API with the `@stacks/wallet-sdk`?

maybe not... idk. but if not, then I imagine our wallet provider will make lots of use of that package (which is unfortunate at some level, as it doesn't seem to be very actively maintained... but maybe it was renamed like so many other stacks repos.)

**Comment by MarvinJanssen** [comment]
Correct, `@stacks/wallet-sdk` was renamed to [`@stacks/keychain`](https://github.com/blockstack/stacks.js/tree/master/packages/keychain).

I think it makes sense to mimic the interface to an extent, like you say, but I honestly have not checked how tightly coupled the packages are. (I assume pretty tight.) So adding a `StacksWalletProvider` in between is probably what we have to do regardless. If we standardise it on the `stacks-wallet-web` side then it opens the door to more wallet providers.

I imagine we'd have a `StacksKeychainProvider` that uses `@stacks/keychain`, and a `StacksJsonRpcProvider` of some sort that can talk to the Ryder bridge. (Again necessitating a standard.)

Here's an example with little thought put into it:

```TS
export interface StacksWalletProviderRpcRequest {
	jsonrpc: '2.0';
	method: 'info', 'exportIdentity' | 'appSignInWithIdentity' | 'requestSignTransaction';
	params?: any[];
	id?: number;
}

interface StacksWalletProviderRpcResponseBase {
	jsonrpc: '2.0';
	id: number;
}

interface StacksWalletProviderRpcResponseSuccess extends StacksWalletProviderRpcResponseBase {
	result: any;
}

interface StacksWalletProviderRpcResponseFailed extends StacksWalletProviderRpcResponseBase {
	error: { code: number, message: string, data?: any };
}

export type StacksWalletProviderRpcResponse = StacksWalletProviderRpcResponseSuccess | StacksWalletProviderRpcResponseFailed;
```

**Comment by friedger** [comment]
Closing this as a non actionable item
